name: SkyPi
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - liblzma=5.8.1=h39f12f2_2
  - libsqlite=3.51.1=h9a5124b_0
  - libzlib=1.3.1=h8359307_2
  - ncurses=6.5=h5e97a16_3
  - openssl=3.6.0=h5503f6c_0
  - pip=25.3=pyh8b19718_0
  - python=3.12.12=h18782d2_1_cpython
  - readline=8.3=h46df422_0
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=h892fb3f_3
  - tzdata=2025c=h8577fbf_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - numpy
  - pillow
  - pip:
    - picamera2
prefix: /Users/daniel/anaconda3/envs/SkyPi
